name: traffic_violation_app
description: Traffic Violation Detection & Fine Payment App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.1
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^17.1.0
  
  # Animations
  animations: ^2.0.11
  lottie: ^3.0.0
  
  # Networking
  http: ^1.2.0
  dio: ^5.4.0
  web_socket_channel: ^3.0.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^20.1.0
  
  # Image
  cached_network_image: ^3.3.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Date & Time
  intl: ^0.20.2
  
  # Utils
  uuid: ^4.3.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/lottie/
